# Generated by Django 2.0.4 on 2018-04-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=40)),
                ('dob', models.DateField()),
                ('citizenship_no', models.CharField(max_length=15)),
                ('contact_no', models.CharField(max_length=10)),
                ('account_no', models.PositiveIntegerField(blank=True, unique=True)),
                ('account_type', models.CharField(choices=[(0, 'Current'), (1, 'Saving')], default=1, max_length=1)),
                ('amount', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
