# Generated by Django 2.0.4 on 2018-05-03 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20180503_0822'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_type', models.CharField(blank=True, choices=[('0', 'Deposit'), ('1', 'Withdraw')], max_length=1)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('branch', models.CharField(blank=True, max_length=20, null=True)),
                ('vouch_no', models.PositiveIntegerField()),
                ('deposite_by', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=20)),
                ('source_of_funds', models.CharField(blank=True, max_length=200, null=True)),
                ('method', models.CharField(choices=[('0', 'Cash'), ('1', 'Cheque')], default='0', max_length=200)),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='deposite',
            name='account',
        ),
        migrations.RenameField(
            model_name='withdaw',
            old_name='account',
            new_name='account_name',
        ),
        migrations.AddField(
            model_name='withdaw',
            name='branch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='withdaw',
            name='check_no',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdaw',
            name='pay_against',
            field=models.CharField(default='santosh', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdaw',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('0', 'Deposit'), ('1', 'Withdraw')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Deposite',
        ),
    ]
