# Generated by Django 2.0.4 on 2018-05-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20180503_0822'),
        ('transaction', '0002_auto_20180503_0854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Withdaw',
            new_name='Withdraw',
        ),
    ]
